name: kirby-stats
type: php
docroot: example
php_version: '8.3'
webserver_type: apache-fpm
router_http_port: '80'
router_https_port: '443'
xdebug_enabled: true
nfs_mount_enabled: false
mutagen_enabled: false
use_dns_when_possible: true
composer_version: '2'
web_environment: []
nodejs_version: '20'
omit_containers: [db, ddev-ssh-agent]
timezone: Europe/Berlin
